    BBPATH .= ":${LAYERDIR}"

    BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
                ${LAYERDIR}/recipes-*/*/*.bbappend"

    BBFILE_COLLECTIONS += "meta-axidma"
    BBFILE_PATTERN_meta-axidma = "^${LAYERDIR}/"
    BBFILE_PRIORITY_meta-axidma = "6"

    LAYERDEPENDS_meta-axidma = "core"
    LAYERSERIES_COMPAT_meta-axidma = "langdale"